<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
* Name:  投票活动分类 中文语言包
*/

// 列信息
$lang['vcl_head_title'] 	  	 = 'Voting classification';

$lang['vcl_vc_id'] 	  	 		 = 'Action category ID';
$lang['vcl_name'] 	  	 		 = 'Name of activity classification';
$lang['vcl_code'] 	  	  		 = 'Identification code';
$lang['vcl_date_add'] 	  	 	 = 'Creation time';
$lang['vcl_status']				 = 'Status';
$lang['vcl_status_on']			 = 'Enable';
$lang['vcl_status_off']			 = 'Enabled';
$lang['vcl_chioce']				 = 'Chioce';
$lang['vcl_operation']			 = 'Operation';
$lang['vcl_search']				 = 'Search';
$lang['vcl_edit']				 = 'Edit';
$lang['vcl_delete']				 = 'Delete';
$lang['vcl_add']				 = 'Add';
$lang['vcl_chioce_all']			 = 'Chioce all';
$lang['vcl_save']			 	 = 'Save';
$lang['vcl_return']			 	 = 'Return';
$lang['vcl_form_title_add']		 = 'Classification of new activities';

//help
$lang['vcl_help_name']			 = 'Please write the name of this activity classification!';
$lang['vcl_help_code']			 = 'The item is not filled, automatically generated by the system!';
$lang['vcl_help_date_add']		 = 'The item is not filled, automatically generated by the system!';
